spring:
  application:
    name: reward-service

  datasource:
    url: jdbc:sqlite:file:rewarddb?mode=memory&cache=shared
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: none
    show-sql: false

  sql:
    init:
      mode: always

server:
  port: 8080

logging:
  level:
    root: INFO
    com.customer.rewards.service: DEBUG

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html